import { SignIn, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";

const Home: NextPage = (props) => {
  const user = useUser();
  console.log(user);
  const { data } = api.group.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {!user.isSignedIn && (
          <SignIn path="/" routing="path" signUpUrl="/sign-up" />
        )}
        {user.user?.id}
        {user.isSignedIn && <SignOutButton />}
        <div>
          {data?.map?.((group) => (
            <div key={group.id}>
              <h1>
                {group.icon}
                {group.name}
              </h1>
              <p>{group.description}</p>
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
