import { Sidebar } from "@/components/sidebar";
import { Button } from "@/components/ui/button";
import { SignIn, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import { useTheme } from "next-themes";
import Head from "next/head";

const Home: NextPage = (_) => {
  const user = useUser();
  const { theme, setTheme } = useTheme();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid min-h-screen bg-background lg:grid-cols-5">
        <Sidebar className="hidden lg:block" userId={user?.user?.id} />
        <div className="text-secondary-foreground">
          {!user.isSignedIn && (
            <SignIn path="/" routing="path" signUpUrl="/sign-up" />
          )}
          <Button
            onClick={() => setTheme(theme === "light" ? "dark" : "light")}
          >
            {theme === "light" ? "Dark" : "Light"}
          </Button>
          <Button
            onClick={() => setTheme(theme === "system" ? "light" : "system")}
          >
            {/* {theme === "system" ? "System OFF" : "System ON"} */}
          </Button>
          {user.isSignedIn && <SignOutButton />}
        </div>
      </main>
    </>
  );
};

export default Home;
